version: "3.8"
services:
    jenkins:
        privileged: true
        user: root
        build:
            context: ./
            dockerfile: ./jenkins.Dockerfile
        image: jenkins
        container_name: jenkins
        restart: always
        volumes:
            -   ~/jenkins_data:/var/jenkins_home
        ports:
            - "8080:8080"
            - "50000:50000"